# Generated by Django 5.0.4 on 2024-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('symptoms', models.TextField(null=True)),
            ],
        ),
    ]
