# Generated by Django 5.0.4 on 2024-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_patentdata_age_alter_patentdata_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentdata',
            name='recdata',
            field=models.TextField(null=True),
        ),
    ]
